In [1]:
import numpy as np
import pandas as pd
iris_df=pd.read_csv('Iris.csv')
iris_df.head

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa

In [2]:
X=iris_df.iloc[:,1:5].values
y=iris_df['Species'].values
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [3]:
from sklearn.tree import DecisionTreeClassifier
dtClassifierModel=DecisionTreeClassifier()
dtClassifierModel.fit(X_train,y_train)
y_preds=dtClassifierModel.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,y_preds))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      1.00      0.97        17
 Iris-virginica       1.00      0.93      0.96        14

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45



## To use PCA for dimensionality reduction , Vaules need to be Normalised first

In [4]:
## Normlizing the input values
from sklearn.preprocessing import MinMaxScaler
mmScalerModel=MinMaxScaler()
X_train=mmScalerModel.fit_transform(X_train)
X_test=mmScalerModel.fit_transform(X_test)
X_train

array([[0.25      , 0.86363636, 0.0877193 , 0.        ],
       [0.72222222, 0.40909091, 0.68421053, 0.58333333],
       [0.44444444, 0.45454545, 0.66666667, 0.70833333],
       [0.36111111, 0.27272727, 0.68421053, 0.79166667],
       [0.66666667, 0.5       , 0.8245614 , 1.        ],
       [0.52777778, 0.        , 0.61403509, 0.58333333],
       [0.80555556, 0.63636364, 0.89473684, 1.        ],
       [0.33333333, 0.09090909, 0.47368421, 0.375     ],
       [0.47222222, 0.31818182, 0.61403509, 0.58333333],
       [0.58333333, 0.45454545, 0.61403509, 0.58333333],
       [0.41666667, 0.81818182, 0.03508772, 0.04166667],
       [0.27777778, 0.68181818, 0.0877193 , 0.04166667],
       [0.5       , 0.31818182, 0.64912281, 0.54166667],
       [0.30555556, 0.54545455, 0.12280702, 0.04166667],
       [0.58333333, 0.40909091, 0.78947368, 0.70833333],
       [0.11111111, 0.45454545, 0.10526316, 0.04166667],
       [0.08333333, 0.40909091, 0.0877193 , 0.04166667],
       [0.16666667, 0.13636364,

## PCA Technique for dimensionality reduction

In [5]:
from sklearn.decomposition import PCA
pcaModel=PCA()
X_train=pcaModel.fit_transform(X_train)
X_test=pcaModel.transform(X_test)
pcaModel.explained_variance_ratio_

array([0.82879406, 0.1303275 , 0.0352085 , 0.00566995])

In [6]:
## So from abhove Array(igen Vector) it seems out of 4 , first 2 values array[0] & array[1] together contributes for 0.95(95%) of total verience 
pcaModel=PCA(n_components=2)  ## considering only 2 values
X_train=pcaModel.fit_transform(X_train)
X_test=pcaModel.transform(X_test)
pcaModel.explained_variance_ratio_

array([0.82879406, 0.1303275 ])

In [7]:
dtClassifierModel.fit(X_train,y_train)
y_preds_pca=dtClassifierModel.predict(X_test)
print(classification_report(y_test,y_preds_pca))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      1.00      0.97        17
 Iris-virginica       1.00      0.93      0.96        14

       accuracy                           0.98        45
      macro avg       0.98      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45



In [8]:
X_train

array([[-0.6883845 ,  0.34872964],
       [ 0.33146566,  0.12439458],
       [ 0.28042475,  0.05679581],
       [ 0.34346068, -0.14062019],
       [ 0.64802793,  0.19320595],
       [ 0.28144341, -0.32463022],
       [ 0.7240118 ,  0.37128657],
       [-0.0347551 , -0.32330919],
       [ 0.20264589, -0.05804728],
       [ 0.22324821,  0.11170692],
       [-0.61963087,  0.3797885 ],
       [-0.6182872 ,  0.19628121],
       [ 0.2092645 , -0.04968754],
       [-0.56082405,  0.08211338],
       [ 0.42178257,  0.06715776],
       [-0.63411469, -0.07979946],
       [-0.64829747, -0.13179983],
       [ 0.16508001, -0.34610701],
       [-0.1382492 , -0.32072661],
       [ 0.62642858,  0.10976756],
       [-0.64138368, -0.09903487],
       [ 0.54671571,  0.12962131],
       [-0.60222776, -0.14800093],
       [ 0.05008513, -0.16349853],
       [ 0.31171278, -0.14387804],
       [-0.7008382 , -0.11175585],
       [ 0.63603559,  0.1587003 ],
       [ 0.68604929,  0.52406316],
       [ 0.44103534,

## Linear Discriminent Analysis(LDA)

In [9]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
ldaModel=LDA(n_components=2)
X_train=ldaModel.fit_transform(X_train,y_train)
X_test=ldaModel.transform(X_test)
dtClassifierModel.fit(X_train,y_train)
y_preds_lda=ldaModel.predict(X_test)
print(classification_report(y_test,y_preds_lda))

                 precision    recall  f1-score   support

    Iris-setosa       0.78      1.00      0.88        14
Iris-versicolor       1.00      0.18      0.30        17
 Iris-virginica       0.58      1.00      0.74        14

       accuracy                           0.69        45
      macro avg       0.79      0.73      0.64        45
   weighted avg       0.80      0.69      0.61        45

