In [1]:
my_list1 = [100,200,300,400]
my_list2 = [200,300,400,500]

In [2]:
my_list1 + my_list2

[100, 200, 300, 400, 200, 300, 400, 500]

## N-Dimensional Arrays

In [3]:
import numpy as np

In [4]:
type(my_list1)

list

In [5]:
transformed_list1 = np.array(my_list1)

In [6]:
transformed_list1

array([100, 200, 300, 400])

In [7]:
type(transformed_list1)

numpy.ndarray

In [8]:
transformed_list2 = np.array(my_list2)

In [9]:
type(transformed_list2)

numpy.ndarray

In [10]:
transformed_list1 + transformed_list2

array([300, 500, 700, 900])

In [11]:
my_list3 = ['Vignesh',100,400]
my_list4 = ['Steve',60,80]

In [12]:
transformed_mylist3 = np.array(my_list3)
transformed_mylist4 = np.array(my_list4)

In [13]:
transformed_mylist3 + transformed_mylist4

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> None

In [14]:
transformed_list1

array([100, 200, 300, 400])

In [15]:
transformed_list2

array([200, 300, 400, 500])

In [16]:
transformed_list1 - transformed_list2

array([-100, -100, -100, -100])

In [17]:
transformed_list1 * transformed_list2

array([ 20000,  60000, 120000, 200000])

In [18]:
transformed_list1 / transformed_list2

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [19]:
np.exp(transformed_list1)

array([2.68811714e+043, 7.22597377e+086, 1.94242640e+130, 5.22146969e+173])

In [20]:
np.log(transformed_list1)

array([4.60517019, 5.29831737, 5.70378247, 5.99146455])

In [21]:
np.sin(transformed_list1)

array([-0.50636564, -0.8732973 , -0.99975584, -0.85091936])

In [22]:
transformed_list1

array([100, 200, 300, 400])

In [24]:
transformed_list1[2]

300

In [25]:
list_of_list = [[100,200,300],[400,500,600],[700,800,900]]

In [26]:
transformed_lol = np.array(list_of_list)

In [27]:
transformed_lol

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [29]:
transformed_lol[1]

array([400, 500, 600])

In [31]:
transformed_lol[1:3]

array([[400, 500, 600],
       [700, 800, 900]])

In [33]:
transformed_lol[1:3,1:3]

array([[500, 600],
       [800, 900]])

In [34]:
transformed_lol[:,1]

array([200, 500, 800])

In [37]:
var1 = np.arange(0,20) #Return values from 0 to 19 (20 is excluded and step size is 1)

In [38]:
type(var1)

numpy.ndarray

In [39]:
np.arange(0,20,4) #Return values from 0 to 16 (20 is excluded and step size is 4)

array([ 0,  4,  8, 12, 16])

In [40]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.random.rand(5) #Generates random values that actually follows Uniform Distribution (0-1)

array([0.48753502, 0.76406648, 0.64145554, 0.67156704, 0.95940113])

In [48]:
np.random.randn(5) #Generates random values that actually follows Normal Distribution

array([ 0.54083649,  0.38038752,  2.27572799, -0.91743881,  1.75953111])

In [49]:
np.random.rand(5,6)

array([[0.94933866, 0.05722889, 0.30939867, 0.90525035, 0.51190838,
        0.41310815],
       [0.87189715, 0.45687103, 0.08724721, 0.98829528, 0.45989691,
        0.99428669],
       [0.20220478, 0.10107019, 0.07967604, 0.25500755, 0.80995635,
        0.15551647],
       [0.36752252, 0.4557826 , 0.84970579, 0.03747274, 0.37991909,
        0.83893544],
       [0.38363854, 0.53244878, 0.49728643, 0.9808183 , 0.56645892,
        0.59909294]])

In [53]:
np.random.randint(5,20) #Returns one random integer between 5 & 19.

12

In [64]:
sample_array = np.random.randint(5,1000,30)

In [66]:
sample_array

array([280, 489,  67, 821, 808, 906, 106, 268, 348, 136, 141, 316, 581,
       145, 324,  72, 948, 676, 758, 824, 370, 544, 648, 344, 644, 970,
       248, 737, 272, 831])

In [69]:
sample_array.reshape(6,5)

array([[280, 489,  67, 821, 808],
       [906, 106, 268, 348, 136],
       [141, 316, 581, 145, 324],
       [ 72, 948, 676, 758, 824],
       [370, 544, 648, 344, 644],
       [970, 248, 737, 272, 831]])

In [70]:
sample_array.max() #Retrieve the max value in the array

970

In [72]:
sample_array.min() #Retrieve the max value in the array

67

In [73]:
sample_array.argmax() #Retrieve the position of the max value

25

In [74]:
sample_array.argmin() #Retrieve the position of the min value

2

In [75]:
sample_array

array([280, 489,  67, 821, 808, 906, 106, 268, 348, 136, 141, 316, 581,
       145, 324,  72, 948, 676, 758, 824, 370, 544, 648, 344, 644, 970,
       248, 737, 272, 831])

In [76]:
sample_array[1] = 100

In [77]:
sample_array

array([280, 100,  67, 821, 808, 906, 106, 268, 348, 136, 141, 316, 581,
       145, 324,  72, 948, 676, 758, 824, 370, 544, 648, 344, 644, 970,
       248, 737, 272, 831])

In [80]:
subset_array = sample_array[0:6]

In [81]:
subset_array

array([280, 100,  67, 821, 808, 906])

In [82]:
subset_array[:] = 100

In [83]:
subset_array

array([100, 100, 100, 100, 100, 100])

In [84]:
sample_array

array([100, 100, 100, 100, 100, 100, 106, 268, 348, 136, 141, 316, 581,
       145, 324,  72, 948, 676, 758, 824, 370, 544, 648, 344, 644, 970,
       248, 737, 272, 831])

In [102]:
sample_array = np.random.randint(5,1000,25)

In [103]:
sample_array

array([462, 842, 467, 100, 751, 537, 924, 947, 167, 766, 927, 402, 464,
       736, 171, 995, 442, 331, 661, 973, 913, 561,  76, 261,  35])

In [104]:
copy_sample_array = sample_array.copy()

In [105]:
copy_sample_array

array([462, 842, 467, 100, 751, 537, 924, 947, 167, 766, 927, 402, 464,
       736, 171, 995, 442, 331, 661, 973, 913, 561,  76, 261,  35])

In [106]:
subset_sample_array = sample_array[0:6]

In [107]:
subset_sample_array

array([462, 842, 467, 100, 751, 537])

In [108]:
subset_sample_array[:] = 100

In [109]:
subset_sample_array

array([100, 100, 100, 100, 100, 100])

In [110]:
sample_array

array([100, 100, 100, 100, 100, 100, 924, 947, 167, 766, 927, 402, 464,
       736, 171, 995, 442, 331, 661, 973, 913, 561,  76, 261,  35])

In [111]:
copy_sample_array

array([462, 842, 467, 100, 751, 537, 924, 947, 167, 766, 927, 402, 464,
       736, 171, 995, 442, 331, 661, 973, 913, 561,  76, 261,  35])

In [112]:
np.mean(copy_sample_array)

556.44

In [113]:
np.std(copy_sample_array)

305.7213214677707

In [114]:
np.var(copy_sample_array)

93465.52639999999

In [116]:
sample_matrix = copy_sample_array.reshape(5,5)

In [117]:
np.linalg.inv(sample_matrix)

array([[-3.42458313e-03,  2.00894778e-03, -1.95872971e-03,
         1.32716910e-03,  2.18900508e-03],
       [ 4.18919084e-03, -2.25733494e-03,  1.73949931e-03,
        -1.73810355e-03, -6.64096529e-04],
       [-2.79232911e-03,  2.56168402e-03, -4.31571994e-04,
         2.10226535e-04,  1.15359876e-04],
       [ 3.79184600e-03, -2.93385858e-03,  3.36254571e-03,
        -1.12218483e-03, -2.38428999e-03],
       [-2.70415240e-05,  9.27051492e-05, -9.24681420e-04,
         1.15096373e-03, -3.56318416e-04]])

In [118]:
import math

In [120]:
math.factorial(5)

120

## Pandas

In [121]:
import pandas as pd

In [122]:
my_dictionary = {'a':10,'b':20,'c':30}

In [126]:
my_list = [10,20,30]
index_list = ['x','y','z']

In [128]:
var = pd.Series(data=my_list, index=index_list)

In [129]:
var

x    10
y    20
z    30
dtype: int64

In [130]:
var['y']

20

In [131]:
student_data1 = {'Cricket':4,'Basketball':3,'Tennis':2}

In [132]:
student_data2 = {'Cricket':5, 'Football': 3, 'Tennis':4}

In [134]:
sports1 = pd.Series(data=student_data1)

In [135]:
sports1

Cricket       4
Basketball    3
Tennis        2
dtype: int64

In [136]:
sports2 = pd.Series(data=student_data2)

In [137]:
sports2

Cricket     5
Football    3
Tennis      4
dtype: int64

In [138]:
sports1 + sports2

Basketball    NaN
Cricket       9.0
Football      NaN
Tennis        6.0
dtype: float64

In [141]:
sample_df = pd.DataFrame(data= np.random.randn(10,5), index = 'A B C D E F G H I J'.split(), columns= 'Score1 Score2 Score3 Score4 Score5'.split())

In [142]:
sample_df

Score1    Score2    Score3    Score4    Score5
A  0.653267  1.003768 -0.971369 -1.970383  0.440987
B -0.880486 -0.509172  1.106688 -0.021892  0.854035
C  0.367641  0.860104  1.335051  0.402704 -2.231040
D -1.405525  2.148181  0.055525 -1.318455  1.248768
E  0.639222 -0.397676  1.469133 -1.771178 -0.575833
F -0.834953 -0.853650  0.355583 -1.551467  0.481310
G -1.404201 -0.520235  1.002873 -1.639894  1.147218
H -0.143992  1.106420  0.767240 -0.862267  0.182364
I  0.860263 -0.148644 -1.003691  1.342034  0.535740
J  0.709983 -1.689958  0.091697  1.448513 -1.762078

In [143]:
sample_df.loc['A','Score3']

-0.9713686677770775

In [144]:
sample_df['Score3']

A   -0.971369
B    1.106688
C    1.335051
D    0.055525
E    1.469133
F    0.355583
G    1.002873
H    0.767240
I   -1.003691
J    0.091697
Name: Score3, dtype: float64

In [ ]:
list_of_list=[[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]]